### ISSUE TITLE
Image is not preloaded

### ISSUE THREAD

**Issue by mathieulawnik** [SAP-samples/s4hana-avc-ui-extension-template#5]
When the extension is deployed on a real system, the image for the selected characteristic value does not appear on the **robot_commonData** view until the value help button is pressed. The image appears immediately when the view is tested locally.

Is there any way to force the system to load the image immediately on the **robot_commonData** view ?

**Comment by florianstephan01** [comment]
I guess you are referring to characteristic 'AVC_RBT_APPLICATION'? ... As none of the values (01 - Sealing / 02 Painting) is flagged as 'default', initially no value is assigned - hence no image is shown.

**Comment by mathieulawnik** [comment]
@florianstephan01 even when the value for the characteristic has previously been set, the image is not preloaded on the extension view. You have to press the value help button (without changing the value) for the images to be preloaded. When you close the value help widget, the image is now visible in the extension view.

**Comment by florianstephan01** [comment]
@mathieulawnik: thanks for clarification. Now i could reproduce it. I created an internal incident for this. If you face a similar issue on an UI Extension you use productively, please open an incident via https://support.sap.com/.
Thanks.
